// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"test/local/ent/appointement"
	"test/local/ent/practitioner"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AppointementCreate is the builder for creating a Appointement entity.
type AppointementCreate struct {
	config
	mutation *AppointementMutation
	hooks    []Hook
}

// SetCreatedAt sets the "CreatedAt" field.
func (_c *AppointementCreate) SetCreatedAt(v time.Time) *AppointementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_c *AppointementCreate) SetNillableCreatedAt(v *time.Time) *AppointementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_c *AppointementCreate) SetUpdatedAt(v time.Time) *AppointementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_c *AppointementCreate) SetNillableUpdatedAt(v *time.Time) *AppointementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTime sets the "Time" field.
func (_c *AppointementCreate) SetTime(v time.Time) *AppointementCreate {
	_c.mutation.SetTime(v)
	return _c
}

// SetNillableTime sets the "Time" field if the given value is not nil.
func (_c *AppointementCreate) SetNillableTime(v *time.Time) *AppointementCreate {
	if v != nil {
		_c.SetTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppointementCreate) SetID(v uuid.UUID) *AppointementCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPractitionerID sets the "practitioner" edge to the Practitioner entity by ID.
func (_c *AppointementCreate) SetPractitionerID(id uuid.UUID) *AppointementCreate {
	_c.mutation.SetPractitionerID(id)
	return _c
}

// SetNillablePractitionerID sets the "practitioner" edge to the Practitioner entity by ID if the given value is not nil.
func (_c *AppointementCreate) SetNillablePractitionerID(id *uuid.UUID) *AppointementCreate {
	if id != nil {
		_c = _c.SetPractitionerID(*id)
	}
	return _c
}

// SetPractitioner sets the "practitioner" edge to the Practitioner entity.
func (_c *AppointementCreate) SetPractitioner(v *Practitioner) *AppointementCreate {
	return _c.SetPractitionerID(v.ID)
}

// Mutation returns the AppointementMutation object of the builder.
func (_c *AppointementCreate) Mutation() *AppointementMutation {
	return _c.mutation
}

// Save creates the Appointement in the database.
func (_c *AppointementCreate) Save(ctx context.Context) (*Appointement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppointementCreate) SaveX(ctx context.Context) *Appointement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppointementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppointementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppointementCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appointement.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appointement.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Time(); !ok {
		v := appointement.DefaultTime
		_c.mutation.SetTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppointementCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "CreatedAt", err: errors.New(`ent: missing required field "Appointement.CreatedAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "UpdatedAt", err: errors.New(`ent: missing required field "Appointement.UpdatedAt"`)}
	}
	if _, ok := _c.mutation.Time(); !ok {
		return &ValidationError{Name: "Time", err: errors.New(`ent: missing required field "Appointement.Time"`)}
	}
	return nil
}

func (_c *AppointementCreate) sqlSave(ctx context.Context) (*Appointement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppointementCreate) createSpec() (*Appointement, *sqlgraph.CreateSpec) {
	var (
		_node = &Appointement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appointement.Table, sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appointement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appointement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Time(); ok {
		_spec.SetField(appointement.FieldTime, field.TypeTime, value)
		_node.Time = value
	}
	if nodes := _c.mutation.PractitionerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appointement.PractitionerTable,
			Columns: []string{appointement.PractitionerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practitioner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.practitioner_appointement = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AppointementCreateBulk is the builder for creating many Appointement entities in bulk.
type AppointementCreateBulk struct {
	config
	err      error
	builders []*AppointementCreate
}

// Save creates the Appointement entities in the database.
func (_c *AppointementCreateBulk) Save(ctx context.Context) ([]*Appointement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Appointement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppointementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppointementCreateBulk) SaveX(ctx context.Context) []*Appointement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppointementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppointementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
