// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"test/local/ent/appointement"
	"test/local/ent/practitioner"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Appointement is the model entity for the Appointement schema.
type Appointement struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "CreatedAt" field.
	CreatedAt time.Time `json:"CreatedAt,omitempty"`
	// UpdatedAt holds the value of the "UpdatedAt" field.
	UpdatedAt time.Time `json:"UpdatedAt,omitempty"`
	// Time holds the value of the "Time" field.
	Time time.Time `json:"Time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AppointementQuery when eager-loading is set.
	Edges                     AppointementEdges `json:"edges"`
	practitioner_appointement *uuid.UUID
	selectValues              sql.SelectValues
}

// AppointementEdges holds the relations/edges for other nodes in the graph.
type AppointementEdges struct {
	// Practitioner holds the value of the practitioner edge.
	Practitioner *Practitioner `json:"practitioner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PractitionerOrErr returns the Practitioner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AppointementEdges) PractitionerOrErr() (*Practitioner, error) {
	if e.Practitioner != nil {
		return e.Practitioner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: practitioner.Label}
	}
	return nil, &NotLoadedError{edge: "practitioner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Appointement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case appointement.FieldCreatedAt, appointement.FieldUpdatedAt, appointement.FieldTime:
			values[i] = new(sql.NullTime)
		case appointement.FieldID:
			values[i] = new(uuid.UUID)
		case appointement.ForeignKeys[0]: // practitioner_appointement
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Appointement fields.
func (_m *Appointement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appointement.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case appointement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field CreatedAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case appointement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field UpdatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case appointement.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Time", values[i])
			} else if value.Valid {
				_m.Time = value.Time
			}
		case appointement.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field practitioner_appointement", values[i])
			} else if value.Valid {
				_m.practitioner_appointement = new(uuid.UUID)
				*_m.practitioner_appointement = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Appointement.
// This includes values selected through modifiers, order, etc.
func (_m *Appointement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPractitioner queries the "practitioner" edge of the Appointement entity.
func (_m *Appointement) QueryPractitioner() *PractitionerQuery {
	return NewAppointementClient(_m.config).QueryPractitioner(_m)
}

// Update returns a builder for updating this Appointement.
// Note that you need to call Appointement.Unwrap() before calling this method if this Appointement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Appointement) Update() *AppointementUpdateOne {
	return NewAppointementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Appointement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Appointement) Unwrap() *Appointement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Appointement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Appointement) String() string {
	var builder strings.Builder
	builder.WriteString("Appointement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("CreatedAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("UpdatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("Time=")
	builder.WriteString(_m.Time.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Appointements is a parsable slice of Appointement.
type Appointements []*Appointement
