// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"test/local/ent/appointement"
	"test/local/ent/practitioner"
	"test/local/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AppointementUpdate is the builder for updating Appointement entities.
type AppointementUpdate struct {
	config
	hooks    []Hook
	mutation *AppointementMutation
}

// Where appends a list predicates to the AppointementUpdate builder.
func (_u *AppointementUpdate) Where(ps ...predicate.Appointement) *AppointementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "CreatedAt" field.
func (_u *AppointementUpdate) SetCreatedAt(v time.Time) *AppointementUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_u *AppointementUpdate) SetNillableCreatedAt(v *time.Time) *AppointementUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_u *AppointementUpdate) SetUpdatedAt(v time.Time) *AppointementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_u *AppointementUpdate) SetNillableUpdatedAt(v *time.Time) *AppointementUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetTime sets the "Time" field.
func (_u *AppointementUpdate) SetTime(v time.Time) *AppointementUpdate {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "Time" field if the given value is not nil.
func (_u *AppointementUpdate) SetNillableTime(v *time.Time) *AppointementUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetPractitionerID sets the "practitioner" edge to the Practitioner entity by ID.
func (_u *AppointementUpdate) SetPractitionerID(id uuid.UUID) *AppointementUpdate {
	_u.mutation.SetPractitionerID(id)
	return _u
}

// SetNillablePractitionerID sets the "practitioner" edge to the Practitioner entity by ID if the given value is not nil.
func (_u *AppointementUpdate) SetNillablePractitionerID(id *uuid.UUID) *AppointementUpdate {
	if id != nil {
		_u = _u.SetPractitionerID(*id)
	}
	return _u
}

// SetPractitioner sets the "practitioner" edge to the Practitioner entity.
func (_u *AppointementUpdate) SetPractitioner(v *Practitioner) *AppointementUpdate {
	return _u.SetPractitionerID(v.ID)
}

// Mutation returns the AppointementMutation object of the builder.
func (_u *AppointementUpdate) Mutation() *AppointementMutation {
	return _u.mutation
}

// ClearPractitioner clears the "practitioner" edge to the Practitioner entity.
func (_u *AppointementUpdate) ClearPractitioner() *AppointementUpdate {
	_u.mutation.ClearPractitioner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppointementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppointementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppointementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppointementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppointementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(appointement.Table, appointement.Columns, sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(appointement.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appointement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(appointement.FieldTime, field.TypeTime, value)
	}
	if _u.mutation.PractitionerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appointement.PractitionerTable,
			Columns: []string{appointement.PractitionerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practitioner.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PractitionerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appointement.PractitionerTable,
			Columns: []string{appointement.PractitionerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practitioner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appointement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppointementUpdateOne is the builder for updating a single Appointement entity.
type AppointementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppointementMutation
}

// SetCreatedAt sets the "CreatedAt" field.
func (_u *AppointementUpdateOne) SetCreatedAt(v time.Time) *AppointementUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_u *AppointementUpdateOne) SetNillableCreatedAt(v *time.Time) *AppointementUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_u *AppointementUpdateOne) SetUpdatedAt(v time.Time) *AppointementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_u *AppointementUpdateOne) SetNillableUpdatedAt(v *time.Time) *AppointementUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetTime sets the "Time" field.
func (_u *AppointementUpdateOne) SetTime(v time.Time) *AppointementUpdateOne {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "Time" field if the given value is not nil.
func (_u *AppointementUpdateOne) SetNillableTime(v *time.Time) *AppointementUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetPractitionerID sets the "practitioner" edge to the Practitioner entity by ID.
func (_u *AppointementUpdateOne) SetPractitionerID(id uuid.UUID) *AppointementUpdateOne {
	_u.mutation.SetPractitionerID(id)
	return _u
}

// SetNillablePractitionerID sets the "practitioner" edge to the Practitioner entity by ID if the given value is not nil.
func (_u *AppointementUpdateOne) SetNillablePractitionerID(id *uuid.UUID) *AppointementUpdateOne {
	if id != nil {
		_u = _u.SetPractitionerID(*id)
	}
	return _u
}

// SetPractitioner sets the "practitioner" edge to the Practitioner entity.
func (_u *AppointementUpdateOne) SetPractitioner(v *Practitioner) *AppointementUpdateOne {
	return _u.SetPractitionerID(v.ID)
}

// Mutation returns the AppointementMutation object of the builder.
func (_u *AppointementUpdateOne) Mutation() *AppointementMutation {
	return _u.mutation
}

// ClearPractitioner clears the "practitioner" edge to the Practitioner entity.
func (_u *AppointementUpdateOne) ClearPractitioner() *AppointementUpdateOne {
	_u.mutation.ClearPractitioner()
	return _u
}

// Where appends a list predicates to the AppointementUpdate builder.
func (_u *AppointementUpdateOne) Where(ps ...predicate.Appointement) *AppointementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppointementUpdateOne) Select(field string, fields ...string) *AppointementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Appointement entity.
func (_u *AppointementUpdateOne) Save(ctx context.Context) (*Appointement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppointementUpdateOne) SaveX(ctx context.Context) *Appointement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppointementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppointementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppointementUpdateOne) sqlSave(ctx context.Context) (_node *Appointement, err error) {
	_spec := sqlgraph.NewUpdateSpec(appointement.Table, appointement.Columns, sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Appointement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appointement.FieldID)
		for _, f := range fields {
			if !appointement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appointement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(appointement.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appointement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(appointement.FieldTime, field.TypeTime, value)
	}
	if _u.mutation.PractitionerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appointement.PractitionerTable,
			Columns: []string{appointement.PractitionerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practitioner.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PractitionerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   appointement.PractitionerTable,
			Columns: []string{appointement.PractitionerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practitioner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Appointement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appointement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
