// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"test/local/ent/migrate"

	"test/local/ent/appointement"
	"test/local/ent/practitioner"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Appointement is the client for interacting with the Appointement builders.
	Appointement *AppointementClient
	// Practitioner is the client for interacting with the Practitioner builders.
	Practitioner *PractitionerClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Appointement = NewAppointementClient(c.config)
	c.Practitioner = NewPractitionerClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Appointement: NewAppointementClient(cfg),
		Practitioner: NewPractitionerClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Appointement: NewAppointementClient(cfg),
		Practitioner: NewPractitionerClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Appointement.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Appointement.Use(hooks...)
	c.Practitioner.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Appointement.Intercept(interceptors...)
	c.Practitioner.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AppointementMutation:
		return c.Appointement.mutate(ctx, m)
	case *PractitionerMutation:
		return c.Practitioner.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AppointementClient is a client for the Appointement schema.
type AppointementClient struct {
	config
}

// NewAppointementClient returns a client for the Appointement from the given config.
func NewAppointementClient(c config) *AppointementClient {
	return &AppointementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appointement.Hooks(f(g(h())))`.
func (c *AppointementClient) Use(hooks ...Hook) {
	c.hooks.Appointement = append(c.hooks.Appointement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `appointement.Intercept(f(g(h())))`.
func (c *AppointementClient) Intercept(interceptors ...Interceptor) {
	c.inters.Appointement = append(c.inters.Appointement, interceptors...)
}

// Create returns a builder for creating a Appointement entity.
func (c *AppointementClient) Create() *AppointementCreate {
	mutation := newAppointementMutation(c.config, OpCreate)
	return &AppointementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Appointement entities.
func (c *AppointementClient) CreateBulk(builders ...*AppointementCreate) *AppointementCreateBulk {
	return &AppointementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppointementClient) MapCreateBulk(slice any, setFunc func(*AppointementCreate, int)) *AppointementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppointementCreateBulk{err: fmt.Errorf("calling to AppointementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppointementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppointementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Appointement.
func (c *AppointementClient) Update() *AppointementUpdate {
	mutation := newAppointementMutation(c.config, OpUpdate)
	return &AppointementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppointementClient) UpdateOne(_m *Appointement) *AppointementUpdateOne {
	mutation := newAppointementMutation(c.config, OpUpdateOne, withAppointement(_m))
	return &AppointementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppointementClient) UpdateOneID(id uuid.UUID) *AppointementUpdateOne {
	mutation := newAppointementMutation(c.config, OpUpdateOne, withAppointementID(id))
	return &AppointementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Appointement.
func (c *AppointementClient) Delete() *AppointementDelete {
	mutation := newAppointementMutation(c.config, OpDelete)
	return &AppointementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppointementClient) DeleteOne(_m *Appointement) *AppointementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppointementClient) DeleteOneID(id uuid.UUID) *AppointementDeleteOne {
	builder := c.Delete().Where(appointement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppointementDeleteOne{builder}
}

// Query returns a query builder for Appointement.
func (c *AppointementClient) Query() *AppointementQuery {
	return &AppointementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAppointement},
		inters: c.Interceptors(),
	}
}

// Get returns a Appointement entity by its id.
func (c *AppointementClient) Get(ctx context.Context, id uuid.UUID) (*Appointement, error) {
	return c.Query().Where(appointement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppointementClient) GetX(ctx context.Context, id uuid.UUID) *Appointement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPractitioner queries the practitioner edge of a Appointement.
func (c *AppointementClient) QueryPractitioner(_m *Appointement) *PractitionerQuery {
	query := (&PractitionerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(appointement.Table, appointement.FieldID, id),
			sqlgraph.To(practitioner.Table, practitioner.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, appointement.PractitionerTable, appointement.PractitionerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AppointementClient) Hooks() []Hook {
	return c.hooks.Appointement
}

// Interceptors returns the client interceptors.
func (c *AppointementClient) Interceptors() []Interceptor {
	return c.inters.Appointement
}

func (c *AppointementClient) mutate(ctx context.Context, m *AppointementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppointementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppointementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppointementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppointementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Appointement mutation op: %q", m.Op())
	}
}

// PractitionerClient is a client for the Practitioner schema.
type PractitionerClient struct {
	config
}

// NewPractitionerClient returns a client for the Practitioner from the given config.
func NewPractitionerClient(c config) *PractitionerClient {
	return &PractitionerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `practitioner.Hooks(f(g(h())))`.
func (c *PractitionerClient) Use(hooks ...Hook) {
	c.hooks.Practitioner = append(c.hooks.Practitioner, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `practitioner.Intercept(f(g(h())))`.
func (c *PractitionerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Practitioner = append(c.inters.Practitioner, interceptors...)
}

// Create returns a builder for creating a Practitioner entity.
func (c *PractitionerClient) Create() *PractitionerCreate {
	mutation := newPractitionerMutation(c.config, OpCreate)
	return &PractitionerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Practitioner entities.
func (c *PractitionerClient) CreateBulk(builders ...*PractitionerCreate) *PractitionerCreateBulk {
	return &PractitionerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PractitionerClient) MapCreateBulk(slice any, setFunc func(*PractitionerCreate, int)) *PractitionerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PractitionerCreateBulk{err: fmt.Errorf("calling to PractitionerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PractitionerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PractitionerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Practitioner.
func (c *PractitionerClient) Update() *PractitionerUpdate {
	mutation := newPractitionerMutation(c.config, OpUpdate)
	return &PractitionerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PractitionerClient) UpdateOne(_m *Practitioner) *PractitionerUpdateOne {
	mutation := newPractitionerMutation(c.config, OpUpdateOne, withPractitioner(_m))
	return &PractitionerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PractitionerClient) UpdateOneID(id uuid.UUID) *PractitionerUpdateOne {
	mutation := newPractitionerMutation(c.config, OpUpdateOne, withPractitionerID(id))
	return &PractitionerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Practitioner.
func (c *PractitionerClient) Delete() *PractitionerDelete {
	mutation := newPractitionerMutation(c.config, OpDelete)
	return &PractitionerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PractitionerClient) DeleteOne(_m *Practitioner) *PractitionerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PractitionerClient) DeleteOneID(id uuid.UUID) *PractitionerDeleteOne {
	builder := c.Delete().Where(practitioner.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PractitionerDeleteOne{builder}
}

// Query returns a query builder for Practitioner.
func (c *PractitionerClient) Query() *PractitionerQuery {
	return &PractitionerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePractitioner},
		inters: c.Interceptors(),
	}
}

// Get returns a Practitioner entity by its id.
func (c *PractitionerClient) Get(ctx context.Context, id uuid.UUID) (*Practitioner, error) {
	return c.Query().Where(practitioner.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PractitionerClient) GetX(ctx context.Context, id uuid.UUID) *Practitioner {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAppointement queries the appointement edge of a Practitioner.
func (c *PractitionerClient) QueryAppointement(_m *Practitioner) *AppointementQuery {
	query := (&AppointementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(practitioner.Table, practitioner.FieldID, id),
			sqlgraph.To(appointement.Table, appointement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, practitioner.AppointementTable, practitioner.AppointementColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PractitionerClient) Hooks() []Hook {
	return c.hooks.Practitioner
}

// Interceptors returns the client interceptors.
func (c *PractitionerClient) Interceptors() []Interceptor {
	return c.inters.Practitioner
}

func (c *PractitionerClient) mutate(ctx context.Context, m *PractitionerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PractitionerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PractitionerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PractitionerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PractitionerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Practitioner mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Appointement, Practitioner []ent.Hook
	}
	inters struct {
		Appointement, Practitioner []ent.Interceptor
	}
)
