// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"test/local/ent/appointement"
	"test/local/ent/practitioner"
	"test/local/ent/predicate"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAppointement = "Appointement"
	TypePractitioner = "Practitioner"
)

// AppointementMutation represents an operation that mutates the Appointement nodes in the graph.
type AppointementMutation struct {
	config
	op                  Op
	typ                 string
	id                  *uuid.UUID
	_CreatedAt          *time.Time
	_UpdatedAt          *time.Time
	_Time               *time.Time
	clearedFields       map[string]struct{}
	practitioner        *uuid.UUID
	clearedpractitioner bool
	done                bool
	oldValue            func(context.Context) (*Appointement, error)
	predicates          []predicate.Appointement
}

var _ ent.Mutation = (*AppointementMutation)(nil)

// appointementOption allows management of the mutation configuration using functional options.
type appointementOption func(*AppointementMutation)

// newAppointementMutation creates new mutation for the Appointement entity.
func newAppointementMutation(c config, op Op, opts ...appointementOption) *AppointementMutation {
	m := &AppointementMutation{
		config:        c,
		op:            op,
		typ:           TypeAppointement,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAppointementID sets the ID field of the mutation.
func withAppointementID(id uuid.UUID) appointementOption {
	return func(m *AppointementMutation) {
		var (
			err   error
			once  sync.Once
			value *Appointement
		)
		m.oldValue = func(ctx context.Context) (*Appointement, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Appointement.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAppointement sets the old Appointement of the mutation.
func withAppointement(node *Appointement) appointementOption {
	return func(m *AppointementMutation) {
		m.oldValue = func(context.Context) (*Appointement, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AppointementMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AppointementMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Appointement entities.
func (m *AppointementMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AppointementMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AppointementMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Appointement.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "CreatedAt" field.
func (m *AppointementMutation) SetCreatedAt(t time.Time) {
	m._CreatedAt = &t
}

// CreatedAt returns the value of the "CreatedAt" field in the mutation.
func (m *AppointementMutation) CreatedAt() (r time.Time, exists bool) {
	v := m._CreatedAt
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "CreatedAt" field's value of the Appointement entity.
// If the Appointement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppointementMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "CreatedAt" field.
func (m *AppointementMutation) ResetCreatedAt() {
	m._CreatedAt = nil
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (m *AppointementMutation) SetUpdatedAt(t time.Time) {
	m._UpdatedAt = &t
}

// UpdatedAt returns the value of the "UpdatedAt" field in the mutation.
func (m *AppointementMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m._UpdatedAt
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "UpdatedAt" field's value of the Appointement entity.
// If the Appointement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppointementMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "UpdatedAt" field.
func (m *AppointementMutation) ResetUpdatedAt() {
	m._UpdatedAt = nil
}

// SetTime sets the "Time" field.
func (m *AppointementMutation) SetTime(t time.Time) {
	m._Time = &t
}

// Time returns the value of the "Time" field in the mutation.
func (m *AppointementMutation) Time() (r time.Time, exists bool) {
	v := m._Time
	if v == nil {
		return
	}
	return *v, true
}

// OldTime returns the old "Time" field's value of the Appointement entity.
// If the Appointement object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppointementMutation) OldTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTime: %w", err)
	}
	return oldValue.Time, nil
}

// ResetTime resets all changes to the "Time" field.
func (m *AppointementMutation) ResetTime() {
	m._Time = nil
}

// SetPractitionerID sets the "practitioner" edge to the Practitioner entity by id.
func (m *AppointementMutation) SetPractitionerID(id uuid.UUID) {
	m.practitioner = &id
}

// ClearPractitioner clears the "practitioner" edge to the Practitioner entity.
func (m *AppointementMutation) ClearPractitioner() {
	m.clearedpractitioner = true
}

// PractitionerCleared reports if the "practitioner" edge to the Practitioner entity was cleared.
func (m *AppointementMutation) PractitionerCleared() bool {
	return m.clearedpractitioner
}

// PractitionerID returns the "practitioner" edge ID in the mutation.
func (m *AppointementMutation) PractitionerID() (id uuid.UUID, exists bool) {
	if m.practitioner != nil {
		return *m.practitioner, true
	}
	return
}

// PractitionerIDs returns the "practitioner" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// PractitionerID instead. It exists only for internal usage by the builders.
func (m *AppointementMutation) PractitionerIDs() (ids []uuid.UUID) {
	if id := m.practitioner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetPractitioner resets all changes to the "practitioner" edge.
func (m *AppointementMutation) ResetPractitioner() {
	m.practitioner = nil
	m.clearedpractitioner = false
}

// Where appends a list predicates to the AppointementMutation builder.
func (m *AppointementMutation) Where(ps ...predicate.Appointement) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AppointementMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AppointementMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Appointement, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AppointementMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AppointementMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Appointement).
func (m *AppointementMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AppointementMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m._CreatedAt != nil {
		fields = append(fields, appointement.FieldCreatedAt)
	}
	if m._UpdatedAt != nil {
		fields = append(fields, appointement.FieldUpdatedAt)
	}
	if m._Time != nil {
		fields = append(fields, appointement.FieldTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AppointementMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case appointement.FieldCreatedAt:
		return m.CreatedAt()
	case appointement.FieldUpdatedAt:
		return m.UpdatedAt()
	case appointement.FieldTime:
		return m.Time()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AppointementMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case appointement.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case appointement.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case appointement.FieldTime:
		return m.OldTime(ctx)
	}
	return nil, fmt.Errorf("unknown Appointement field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AppointementMutation) SetField(name string, value ent.Value) error {
	switch name {
	case appointement.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case appointement.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case appointement.FieldTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTime(v)
		return nil
	}
	return fmt.Errorf("unknown Appointement field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AppointementMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AppointementMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AppointementMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Appointement numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AppointementMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AppointementMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AppointementMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Appointement nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AppointementMutation) ResetField(name string) error {
	switch name {
	case appointement.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case appointement.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case appointement.FieldTime:
		m.ResetTime()
		return nil
	}
	return fmt.Errorf("unknown Appointement field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AppointementMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.practitioner != nil {
		edges = append(edges, appointement.EdgePractitioner)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AppointementMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case appointement.EdgePractitioner:
		if id := m.practitioner; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AppointementMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AppointementMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AppointementMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedpractitioner {
		edges = append(edges, appointement.EdgePractitioner)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AppointementMutation) EdgeCleared(name string) bool {
	switch name {
	case appointement.EdgePractitioner:
		return m.clearedpractitioner
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AppointementMutation) ClearEdge(name string) error {
	switch name {
	case appointement.EdgePractitioner:
		m.ClearPractitioner()
		return nil
	}
	return fmt.Errorf("unknown Appointement unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AppointementMutation) ResetEdge(name string) error {
	switch name {
	case appointement.EdgePractitioner:
		m.ResetPractitioner()
		return nil
	}
	return fmt.Errorf("unknown Appointement edge %s", name)
}

// PractitionerMutation represents an operation that mutates the Practitioner nodes in the graph.
type PractitionerMutation struct {
	config
	op                  Op
	typ                 string
	id                  *uuid.UUID
	_CreatedAt          *time.Time
	_UpdatedAt          *time.Time
	clearedFields       map[string]struct{}
	appointement        map[uuid.UUID]struct{}
	removedappointement map[uuid.UUID]struct{}
	clearedappointement bool
	done                bool
	oldValue            func(context.Context) (*Practitioner, error)
	predicates          []predicate.Practitioner
}

var _ ent.Mutation = (*PractitionerMutation)(nil)

// practitionerOption allows management of the mutation configuration using functional options.
type practitionerOption func(*PractitionerMutation)

// newPractitionerMutation creates new mutation for the Practitioner entity.
func newPractitionerMutation(c config, op Op, opts ...practitionerOption) *PractitionerMutation {
	m := &PractitionerMutation{
		config:        c,
		op:            op,
		typ:           TypePractitioner,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPractitionerID sets the ID field of the mutation.
func withPractitionerID(id uuid.UUID) practitionerOption {
	return func(m *PractitionerMutation) {
		var (
			err   error
			once  sync.Once
			value *Practitioner
		)
		m.oldValue = func(ctx context.Context) (*Practitioner, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Practitioner.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPractitioner sets the old Practitioner of the mutation.
func withPractitioner(node *Practitioner) practitionerOption {
	return func(m *PractitionerMutation) {
		m.oldValue = func(context.Context) (*Practitioner, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PractitionerMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PractitionerMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Practitioner entities.
func (m *PractitionerMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PractitionerMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PractitionerMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Practitioner.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "CreatedAt" field.
func (m *PractitionerMutation) SetCreatedAt(t time.Time) {
	m._CreatedAt = &t
}

// CreatedAt returns the value of the "CreatedAt" field in the mutation.
func (m *PractitionerMutation) CreatedAt() (r time.Time, exists bool) {
	v := m._CreatedAt
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "CreatedAt" field's value of the Practitioner entity.
// If the Practitioner object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PractitionerMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "CreatedAt" field.
func (m *PractitionerMutation) ResetCreatedAt() {
	m._CreatedAt = nil
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (m *PractitionerMutation) SetUpdatedAt(t time.Time) {
	m._UpdatedAt = &t
}

// UpdatedAt returns the value of the "UpdatedAt" field in the mutation.
func (m *PractitionerMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m._UpdatedAt
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "UpdatedAt" field's value of the Practitioner entity.
// If the Practitioner object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PractitionerMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "UpdatedAt" field.
func (m *PractitionerMutation) ResetUpdatedAt() {
	m._UpdatedAt = nil
}

// AddAppointementIDs adds the "appointement" edge to the Appointement entity by ids.
func (m *PractitionerMutation) AddAppointementIDs(ids ...uuid.UUID) {
	if m.appointement == nil {
		m.appointement = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.appointement[ids[i]] = struct{}{}
	}
}

// ClearAppointement clears the "appointement" edge to the Appointement entity.
func (m *PractitionerMutation) ClearAppointement() {
	m.clearedappointement = true
}

// AppointementCleared reports if the "appointement" edge to the Appointement entity was cleared.
func (m *PractitionerMutation) AppointementCleared() bool {
	return m.clearedappointement
}

// RemoveAppointementIDs removes the "appointement" edge to the Appointement entity by IDs.
func (m *PractitionerMutation) RemoveAppointementIDs(ids ...uuid.UUID) {
	if m.removedappointement == nil {
		m.removedappointement = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.appointement, ids[i])
		m.removedappointement[ids[i]] = struct{}{}
	}
}

// RemovedAppointement returns the removed IDs of the "appointement" edge to the Appointement entity.
func (m *PractitionerMutation) RemovedAppointementIDs() (ids []uuid.UUID) {
	for id := range m.removedappointement {
		ids = append(ids, id)
	}
	return
}

// AppointementIDs returns the "appointement" edge IDs in the mutation.
func (m *PractitionerMutation) AppointementIDs() (ids []uuid.UUID) {
	for id := range m.appointement {
		ids = append(ids, id)
	}
	return
}

// ResetAppointement resets all changes to the "appointement" edge.
func (m *PractitionerMutation) ResetAppointement() {
	m.appointement = nil
	m.clearedappointement = false
	m.removedappointement = nil
}

// Where appends a list predicates to the PractitionerMutation builder.
func (m *PractitionerMutation) Where(ps ...predicate.Practitioner) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PractitionerMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PractitionerMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Practitioner, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PractitionerMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PractitionerMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Practitioner).
func (m *PractitionerMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PractitionerMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m._CreatedAt != nil {
		fields = append(fields, practitioner.FieldCreatedAt)
	}
	if m._UpdatedAt != nil {
		fields = append(fields, practitioner.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PractitionerMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case practitioner.FieldCreatedAt:
		return m.CreatedAt()
	case practitioner.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PractitionerMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case practitioner.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case practitioner.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Practitioner field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PractitionerMutation) SetField(name string, value ent.Value) error {
	switch name {
	case practitioner.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case practitioner.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Practitioner field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PractitionerMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PractitionerMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PractitionerMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Practitioner numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PractitionerMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PractitionerMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PractitionerMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Practitioner nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PractitionerMutation) ResetField(name string) error {
	switch name {
	case practitioner.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case practitioner.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Practitioner field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PractitionerMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.appointement != nil {
		edges = append(edges, practitioner.EdgeAppointement)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PractitionerMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case practitioner.EdgeAppointement:
		ids := make([]ent.Value, 0, len(m.appointement))
		for id := range m.appointement {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PractitionerMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedappointement != nil {
		edges = append(edges, practitioner.EdgeAppointement)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PractitionerMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case practitioner.EdgeAppointement:
		ids := make([]ent.Value, 0, len(m.removedappointement))
		for id := range m.removedappointement {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PractitionerMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedappointement {
		edges = append(edges, practitioner.EdgeAppointement)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PractitionerMutation) EdgeCleared(name string) bool {
	switch name {
	case practitioner.EdgeAppointement:
		return m.clearedappointement
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PractitionerMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Practitioner unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PractitionerMutation) ResetEdge(name string) error {
	switch name {
	case practitioner.EdgeAppointement:
		m.ResetAppointement()
		return nil
	}
	return fmt.Errorf("unknown Practitioner edge %s", name)
}
