// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"test/local/ent/practitioner"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Practitioner is the model entity for the Practitioner schema.
type Practitioner struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "CreatedAt" field.
	CreatedAt time.Time `json:"CreatedAt,omitempty"`
	// UpdatedAt holds the value of the "UpdatedAt" field.
	UpdatedAt time.Time `json:"UpdatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PractitionerQuery when eager-loading is set.
	Edges        PractitionerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PractitionerEdges holds the relations/edges for other nodes in the graph.
type PractitionerEdges struct {
	// Appointement holds the value of the appointement edge.
	Appointement []*Appointement `json:"appointement,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AppointementOrErr returns the Appointement value or an error if the edge
// was not loaded in eager-loading.
func (e PractitionerEdges) AppointementOrErr() ([]*Appointement, error) {
	if e.loadedTypes[0] {
		return e.Appointement, nil
	}
	return nil, &NotLoadedError{edge: "appointement"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Practitioner) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case practitioner.FieldCreatedAt, practitioner.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case practitioner.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Practitioner fields.
func (_m *Practitioner) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case practitioner.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case practitioner.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field CreatedAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case practitioner.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field UpdatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Practitioner.
// This includes values selected through modifiers, order, etc.
func (_m *Practitioner) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAppointement queries the "appointement" edge of the Practitioner entity.
func (_m *Practitioner) QueryAppointement() *AppointementQuery {
	return NewPractitionerClient(_m.config).QueryAppointement(_m)
}

// Update returns a builder for updating this Practitioner.
// Note that you need to call Practitioner.Unwrap() before calling this method if this Practitioner
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Practitioner) Update() *PractitionerUpdateOne {
	return NewPractitionerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Practitioner entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Practitioner) Unwrap() *Practitioner {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Practitioner is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Practitioner) String() string {
	var builder strings.Builder
	builder.WriteString("Practitioner(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("CreatedAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("UpdatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Practitioners is a parsable slice of Practitioner.
type Practitioners []*Practitioner
