// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"test/local/ent/practitioner"
	"test/local/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PractitionerDelete is the builder for deleting a Practitioner entity.
type PractitionerDelete struct {
	config
	hooks    []Hook
	mutation *PractitionerMutation
}

// Where appends a list predicates to the PractitionerDelete builder.
func (_d *PractitionerDelete) Where(ps ...predicate.Practitioner) *PractitionerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PractitionerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PractitionerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PractitionerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(practitioner.Table, sqlgraph.NewFieldSpec(practitioner.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PractitionerDeleteOne is the builder for deleting a single Practitioner entity.
type PractitionerDeleteOne struct {
	_d *PractitionerDelete
}

// Where appends a list predicates to the PractitionerDelete builder.
func (_d *PractitionerDeleteOne) Where(ps ...predicate.Practitioner) *PractitionerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PractitionerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{practitioner.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PractitionerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
