// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"test/local/ent/appointement"
	"test/local/ent/practitioner"
	"test/local/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PractitionerUpdate is the builder for updating Practitioner entities.
type PractitionerUpdate struct {
	config
	hooks    []Hook
	mutation *PractitionerMutation
}

// Where appends a list predicates to the PractitionerUpdate builder.
func (_u *PractitionerUpdate) Where(ps ...predicate.Practitioner) *PractitionerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "CreatedAt" field.
func (_u *PractitionerUpdate) SetCreatedAt(v time.Time) *PractitionerUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_u *PractitionerUpdate) SetNillableCreatedAt(v *time.Time) *PractitionerUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_u *PractitionerUpdate) SetUpdatedAt(v time.Time) *PractitionerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_u *PractitionerUpdate) SetNillableUpdatedAt(v *time.Time) *PractitionerUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddAppointementIDs adds the "appointement" edge to the Appointement entity by IDs.
func (_u *PractitionerUpdate) AddAppointementIDs(ids ...uuid.UUID) *PractitionerUpdate {
	_u.mutation.AddAppointementIDs(ids...)
	return _u
}

// AddAppointement adds the "appointement" edges to the Appointement entity.
func (_u *PractitionerUpdate) AddAppointement(v ...*Appointement) *PractitionerUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAppointementIDs(ids...)
}

// Mutation returns the PractitionerMutation object of the builder.
func (_u *PractitionerUpdate) Mutation() *PractitionerMutation {
	return _u.mutation
}

// ClearAppointement clears all "appointement" edges to the Appointement entity.
func (_u *PractitionerUpdate) ClearAppointement() *PractitionerUpdate {
	_u.mutation.ClearAppointement()
	return _u
}

// RemoveAppointementIDs removes the "appointement" edge to Appointement entities by IDs.
func (_u *PractitionerUpdate) RemoveAppointementIDs(ids ...uuid.UUID) *PractitionerUpdate {
	_u.mutation.RemoveAppointementIDs(ids...)
	return _u
}

// RemoveAppointement removes "appointement" edges to Appointement entities.
func (_u *PractitionerUpdate) RemoveAppointement(v ...*Appointement) *PractitionerUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAppointementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PractitionerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PractitionerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PractitionerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PractitionerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PractitionerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(practitioner.Table, practitioner.Columns, sqlgraph.NewFieldSpec(practitioner.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(practitioner.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(practitioner.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AppointementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practitioner.AppointementTable,
			Columns: []string{practitioner.AppointementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAppointementIDs(); len(nodes) > 0 && !_u.mutation.AppointementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practitioner.AppointementTable,
			Columns: []string{practitioner.AppointementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppointementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practitioner.AppointementTable,
			Columns: []string{practitioner.AppointementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{practitioner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PractitionerUpdateOne is the builder for updating a single Practitioner entity.
type PractitionerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PractitionerMutation
}

// SetCreatedAt sets the "CreatedAt" field.
func (_u *PractitionerUpdateOne) SetCreatedAt(v time.Time) *PractitionerUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_u *PractitionerUpdateOne) SetNillableCreatedAt(v *time.Time) *PractitionerUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_u *PractitionerUpdateOne) SetUpdatedAt(v time.Time) *PractitionerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_u *PractitionerUpdateOne) SetNillableUpdatedAt(v *time.Time) *PractitionerUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddAppointementIDs adds the "appointement" edge to the Appointement entity by IDs.
func (_u *PractitionerUpdateOne) AddAppointementIDs(ids ...uuid.UUID) *PractitionerUpdateOne {
	_u.mutation.AddAppointementIDs(ids...)
	return _u
}

// AddAppointement adds the "appointement" edges to the Appointement entity.
func (_u *PractitionerUpdateOne) AddAppointement(v ...*Appointement) *PractitionerUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAppointementIDs(ids...)
}

// Mutation returns the PractitionerMutation object of the builder.
func (_u *PractitionerUpdateOne) Mutation() *PractitionerMutation {
	return _u.mutation
}

// ClearAppointement clears all "appointement" edges to the Appointement entity.
func (_u *PractitionerUpdateOne) ClearAppointement() *PractitionerUpdateOne {
	_u.mutation.ClearAppointement()
	return _u
}

// RemoveAppointementIDs removes the "appointement" edge to Appointement entities by IDs.
func (_u *PractitionerUpdateOne) RemoveAppointementIDs(ids ...uuid.UUID) *PractitionerUpdateOne {
	_u.mutation.RemoveAppointementIDs(ids...)
	return _u
}

// RemoveAppointement removes "appointement" edges to Appointement entities.
func (_u *PractitionerUpdateOne) RemoveAppointement(v ...*Appointement) *PractitionerUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAppointementIDs(ids...)
}

// Where appends a list predicates to the PractitionerUpdate builder.
func (_u *PractitionerUpdateOne) Where(ps ...predicate.Practitioner) *PractitionerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PractitionerUpdateOne) Select(field string, fields ...string) *PractitionerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Practitioner entity.
func (_u *PractitionerUpdateOne) Save(ctx context.Context) (*Practitioner, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PractitionerUpdateOne) SaveX(ctx context.Context) *Practitioner {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PractitionerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PractitionerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PractitionerUpdateOne) sqlSave(ctx context.Context) (_node *Practitioner, err error) {
	_spec := sqlgraph.NewUpdateSpec(practitioner.Table, practitioner.Columns, sqlgraph.NewFieldSpec(practitioner.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Practitioner.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, practitioner.FieldID)
		for _, f := range fields {
			if !practitioner.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != practitioner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(practitioner.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(practitioner.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AppointementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practitioner.AppointementTable,
			Columns: []string{practitioner.AppointementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAppointementIDs(); len(nodes) > 0 && !_u.mutation.AppointementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practitioner.AppointementTable,
			Columns: []string{practitioner.AppointementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppointementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practitioner.AppointementTable,
			Columns: []string{practitioner.AppointementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(appointement.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Practitioner{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{practitioner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
