// Code generated by ent, DO NOT EDIT.

package ent

import (
	"test/local/ent/appointement"
	"test/local/ent/practitioner"
	"test/local/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appointementFields := schema.Appointement{}.Fields()
	_ = appointementFields
	// appointementDescCreatedAt is the schema descriptor for CreatedAt field.
	appointementDescCreatedAt := appointementFields[1].Descriptor()
	// appointement.DefaultCreatedAt holds the default value on creation for the CreatedAt field.
	appointement.DefaultCreatedAt = appointementDescCreatedAt.Default.(time.Time)
	// appointementDescUpdatedAt is the schema descriptor for UpdatedAt field.
	appointementDescUpdatedAt := appointementFields[2].Descriptor()
	// appointement.DefaultUpdatedAt holds the default value on creation for the UpdatedAt field.
	appointement.DefaultUpdatedAt = appointementDescUpdatedAt.Default.(time.Time)
	// appointementDescTime is the schema descriptor for Time field.
	appointementDescTime := appointementFields[3].Descriptor()
	// appointement.DefaultTime holds the default value on creation for the Time field.
	appointement.DefaultTime = appointementDescTime.Default.(time.Time)
	practitionerFields := schema.Practitioner{}.Fields()
	_ = practitionerFields
	// practitionerDescCreatedAt is the schema descriptor for CreatedAt field.
	practitionerDescCreatedAt := practitionerFields[1].Descriptor()
	// practitioner.DefaultCreatedAt holds the default value on creation for the CreatedAt field.
	practitioner.DefaultCreatedAt = practitionerDescCreatedAt.Default.(time.Time)
	// practitionerDescUpdatedAt is the schema descriptor for UpdatedAt field.
	practitionerDescUpdatedAt := practitionerFields[2].Descriptor()
	// practitioner.DefaultUpdatedAt holds the default value on creation for the UpdatedAt field.
	practitioner.DefaultUpdatedAt = practitionerDescUpdatedAt.Default.(time.Time)
}
