// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppointementsColumns holds the columns for the "appointements" table.
	AppointementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "time", Type: field.TypeTime},
		{Name: "practitioner_appointement", Type: field.TypeUUID, Nullable: true},
	}
	// AppointementsTable holds the schema information for the "appointements" table.
	AppointementsTable = &schema.Table{
		Name:       "appointements",
		Columns:    AppointementsColumns,
		PrimaryKey: []*schema.Column{AppointementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "appointements_practitioners_appointement",
				Columns:    []*schema.Column{AppointementsColumns[4]},
				RefColumns: []*schema.Column{PractitionersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PractitionersColumns holds the columns for the "practitioners" table.
	PractitionersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PractitionersTable holds the schema information for the "practitioners" table.
	PractitionersTable = &schema.Table{
		Name:       "practitioners",
		Columns:    PractitionersColumns,
		PrimaryKey: []*schema.Column{PractitionersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppointementsTable,
		PractitionersTable,
	}
)

func init() {
	AppointementsTable.ForeignKeys[0].RefTable = PractitionersTable
}
