// Code generated by ent, DO NOT EDIT.

package practitioner

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the practitioner type in the database.
	Label = "practitioner"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAppointement holds the string denoting the appointement edge name in mutations.
	EdgeAppointement = "appointement"
	// Table holds the table name of the practitioner in the database.
	Table = "practitioners"
	// AppointementTable is the table that holds the appointement relation/edge.
	AppointementTable = "appointements"
	// AppointementInverseTable is the table name for the Appointement entity.
	// It exists in this package in order to avoid circular dependency with the "appointement" package.
	AppointementInverseTable = "appointements"
	// AppointementColumn is the table column denoting the appointement relation/edge.
	AppointementColumn = "practitioner_appointement"
)

// Columns holds all SQL columns for practitioner fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "CreatedAt" field.
	DefaultCreatedAt time.Time
	// DefaultUpdatedAt holds the default value on creation for the "UpdatedAt" field.
	DefaultUpdatedAt time.Time
)

// OrderOption defines the ordering options for the Practitioner queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the CreatedAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the UpdatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAppointementCount orders the results by appointement count.
func ByAppointementCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAppointementStep(), opts...)
	}
}

// ByAppointement orders the results by appointement terms.
func ByAppointement(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAppointementStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAppointementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AppointementInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AppointementTable, AppointementColumn),
	)
}
