// Code generated by ent, DO NOT EDIT.

package appointement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the appointement type in the database.
	Label = "appointement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// EdgePractitioner holds the string denoting the practitioner edge name in mutations.
	EdgePractitioner = "practitioner"
	// Table holds the table name of the appointement in the database.
	Table = "appointements"
	// PractitionerTable is the table that holds the practitioner relation/edge.
	PractitionerTable = "appointements"
	// PractitionerInverseTable is the table name for the Practitioner entity.
	// It exists in this package in order to avoid circular dependency with the "practitioner" package.
	PractitionerInverseTable = "practitioners"
	// PractitionerColumn is the table column denoting the practitioner relation/edge.
	PractitionerColumn = "practitioner_appointement"
)

// Columns holds all SQL columns for appointement fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "appointements"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"practitioner_appointement",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "CreatedAt" field.
	DefaultCreatedAt time.Time
	// DefaultUpdatedAt holds the default value on creation for the "UpdatedAt" field.
	DefaultUpdatedAt time.Time
	// DefaultTime holds the default value on creation for the "Time" field.
	DefaultTime time.Time
)

// OrderOption defines the ordering options for the Appointement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the CreatedAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the UpdatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTime orders the results by the Time field.
func ByTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTime, opts...).ToFunc()
}

// ByPractitionerField orders the results by practitioner field.
func ByPractitionerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPractitionerStep(), sql.OrderByField(field, opts...))
	}
}
func newPractitionerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PractitionerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PractitionerTable, PractitionerColumn),
	)
}
