// Code generated by ent, DO NOT EDIT.

package appointement

import (
	"test/local/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Appointement {
	return predicate.Appointement(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "CreatedAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "UpdatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldEQ(FieldUpdatedAt, v))
}

// Time applies equality check predicate on the "Time" field. It's identical to TimeEQ.
func Time(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldEQ(FieldTime, v))
}

// CreatedAtEQ applies the EQ predicate on the "CreatedAt" field.
func CreatedAtEQ(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "CreatedAt" field.
func CreatedAtNEQ(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "CreatedAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "CreatedAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "CreatedAt" field.
func CreatedAtGT(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "CreatedAt" field.
func CreatedAtGTE(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "CreatedAt" field.
func CreatedAtLT(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "CreatedAt" field.
func CreatedAtLTE(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "UpdatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "UpdatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "UpdatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "UpdatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "UpdatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "UpdatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "UpdatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "UpdatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldLTE(FieldUpdatedAt, v))
}

// TimeEQ applies the EQ predicate on the "Time" field.
func TimeEQ(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "Time" field.
func TimeNEQ(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "Time" field.
func TimeIn(vs ...time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "Time" field.
func TimeNotIn(vs ...time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "Time" field.
func TimeGT(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "Time" field.
func TimeGTE(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "Time" field.
func TimeLT(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "Time" field.
func TimeLTE(v time.Time) predicate.Appointement {
	return predicate.Appointement(sql.FieldLTE(FieldTime, v))
}

// HasPractitioner applies the HasEdge predicate on the "practitioner" edge.
func HasPractitioner() predicate.Appointement {
	return predicate.Appointement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PractitionerTable, PractitionerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPractitionerWith applies the HasEdge predicate on the "practitioner" edge with a given conditions (other predicates).
func HasPractitionerWith(preds ...predicate.Practitioner) predicate.Appointement {
	return predicate.Appointement(func(s *sql.Selector) {
		step := newPractitionerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Appointement) predicate.Appointement {
	return predicate.Appointement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Appointement) predicate.Appointement {
	return predicate.Appointement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Appointement) predicate.Appointement {
	return predicate.Appointement(sql.NotPredicates(p))
}
