// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Appointement is the predicate function for appointement builders.
type Appointement func(*sql.Selector)

// Practitioner is the predicate function for practitioner builders.
type Practitioner func(*sql.Selector)
